oriente_web/config/urls.py
from django.contrib import admin
from django.urls import path, include

from documentos.views import DocumentoPesquisaFormView as IndexView

from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(title="Oriente Web")

urlpatterns = [
    path('', IndexView.as_view(), name = "index"),
    path('admin/', admin.site.urls),
    path('documentos/', include('documentos.urls')),
    path('api/', include('documentos.api_urls')),
    path('api/schema', schema_view),
]

oriente_web/documentos/urls.py
from django.urls import path, include
from . import views

app_name = "documentos"

urlpatterns = [
    path("", views.DocumentoPesquisaFormView.as_view(), name = "documento_pesquisa_form"),
    path("documento/<int:pk>/", views.DocumentoDetailView.as_view(), name = "documento_detail"),
    path("documento_ajax_detail/", views.documento_ajax_detail, name = "documento_ajax_detail"),
    path('repositorios/', views.quantidade_documentos_repositorios, name='repositorios'),
]

oriente_web/documentos/models.py
from urllib.parse import urlparse, ParseResult

from django.db import models


def toggle_http_https(url):
    u = urlparse(url)

    method = "http"
    if u[0] == "http":
        method = "https"

    return ParseResult(method, *u[1:]).geturl()


class UrlNotStr(Exception):
    pass


class TimeStempedMixin(models.Model):
    criado_em = models.DateTimeField(auto_now_add=True)
    editado_em = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Documento(TimeStempedMixin):
    """Documento
    Modelo que representa um documento do corpus
    url: endereço onde pode-se encontrar informações sobre o documento
    titulo: titulo do documento
    url_arquivo: endereço onde pode-se encontrar o documento completo
    """
    url = models.URLField(unique=True)
    titulo = models.CharField(max_length=255)
    url_arquivo = models.URLField(unique=True)
    sync = models.BooleanField()

    objects = models.Manager()

    def __str__(self):
        return self.url

    @classmethod
    def get_by_url(cls, a_url=None):
        """
        Get documento por url independente de http ou https
        :param a_url: [http:https]://url
        :return: Documento
        """
        assert type(a_url) is str, "Url não é string"

        b_url = toggle_http_https(a_url)
        a_query = models.Q(url=a_url)
        b_query = models.Q(url=b_url)
        return cls.objects.get(a_query | b_query)


class Recomendacao(TimeStempedMixin):
    """Recomendacao
    Modelo que relaciona dois documentos destintos com um fator
    A relação é simetrica, para cara relação existe origem para
    os dois Documentos
    """
    documento_origem = models.ForeignKey(Documento, on_delete=models.CASCADE, related_name="recomendacoes")
    documento_destino = models.ForeignKey(Documento, on_delete=models.CASCADE, related_name="recomendacoes_destino")
    fator = models.FloatField()

    objects = models.Manager()

    class Meta:
        ordering = ("-fator",)
        verbose_name = "Recomendação"
        verbose_name_plural = "Recomendações"
        unique_together = ("documento_origem", "documento_destino")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        queryset = Recomendacao.objects.filter(
            documento_origem=self.documento_destino,
            documento_destino=self.documento_origem,
        )
        if queryset.count() < 1:
            Recomendacao.objects.create(
                documento_origem=self.documento_destino,
                documento_destino=self.documento_origem,
                fator=self.fator,
            )

oriente_web/documentos/forms.py
from django import forms

class DocumentoPesquisaForm(forms.Form):
    url = forms.URLField()

oriente_web/documentos/views.py
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    DetailView,
    FormView
)

from .forms import DocumentoPesquisaForm
from .models import Documento, Recomendacao


class DocumentoPesquisaFormView(FormView):
    form_class = DocumentoPesquisaForm
    template_name = "documentos/documento_pesquisa_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_documentos"] = Documento.objects.all().count()
        context["total_recomendacoes"] = Recomendacao.objects.all().count()
        return context

    def form_valid(self, form):
        get_url = form.cleaned_data["url"]
        
        try:
            documento = Documento.get_by_url(a_url=get_url)
        except Documento.DoesNotExist:
            raise Http404

        self.success_url = reverse_lazy("documentos:documento_detail", kwargs={"pk": documento.pk})
        return super().form_valid(form)


class DocumentoDetailView(DetailView):
    model = Documento
    template_name = "documentos/documento_detail.html"


def documento_ajax_detail(request):
    template_name = "documentos/documento_ajax_detail.html"
    context = {}

    get_url = request.GET.get("url", None)

    if get_url is not None:
        try:
            documento = Documento.documento = Documento.get_by_url(a_url=get_url)
            context["documento"] = documento
        except Documento.DoesNotExist:
            pass

    return render(request, template_name, context)


def quantidade_documentos_repositorios(request):
    template_name = 'documentos/quantidade_documentos_repositorios.html'
    context = {}
    repositorios = ['repositorio.uft.edu.br', 'acervodigital.ufpr.br', 'sigmauft.pythonanywhere.com',
                    'repositorio.bc.ufg.br']

    context['repositorios'] = {}
    for repositorio in repositorios:
        context['repositorios'][repositorio] = Documento.objects.filter(url__icontains=repositorio).count()

    return render(request, template_name, context)

oriente_web/documentos/templates/documentos/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <link href="https://fonts.googleapis.com/css?family=Arvo" rel="stylesheet">        
        <title>
            Oriente Web
        </title>
        <style>
            
            .center{
                align-content: center;
                margin: auto;
                text-align: center;
            }
            
            .lightblue{
                color: lightblue;
            }
            
            h1, h2, h3, h4, h5, h6 {
                color: #444444;
            }
            a.sitelink{
                text-decoration: none;
                color: indianred;
            }
            
        </style>
    </head>

    <body>
        <div class="center">
            <h1  style="color: indianred;"><a class="sitelink" href="{% url 'documentos:documento_pesquisa_form' %}">Oriente Web</a></h1>
        {% block body %}

        {% endblock body %}
        </div>
    </body>
</html>

oriente_web/documentos/templates/documentos/documento_ajax_detail.html
<ul id="oriente_lista_recomendacoes">
{% if documento %}
    {% for recomendacao in documento.recomendacoes.all %}
    <li><a href="{{recomendacao.documento_destino.url}}" target="_blank">{{recomendacao.documento_destino.titulo}}</a></li>
    {% empty %}
    <li>Não tem recomendações para este documento!</li>
    {% endfor %}
{% else %}
    <li>Documento não registrado!</li>
{% endif %}
</ul>

oriente_web/documentos/templates/documentos/documento_detail.html
{% extends 'documentos/base.html' %}

{% block body %}

<h2>Recomendações para {{object.url}}</h2>
<h2>{{object.titulo}}</h2>


<ol>
{% for recomendacao in object.recomendacoes.all %}
    <li><a target="_blank" href="{{recomendacao.documento_destino}}">{{recomendacao.documento_destino.titulo}}</a></li>
{% empty %}
    <li>Sem recomendações</li>
{% endfor %}
</ol>
{% endblock body %}

oriente_web/documentos/templates/documentos/documento_pesquisa_form.html
{% extends 'documentos/base.html' %}

{% block body %}

    <h2>Total de <b class="lightblue">{{total_documentos}}</b> Documentos</h2>
    
    <h2>Total de <b class="lightblue">{{total_recomendacoes}}</b> Recomendações</h2>

    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="pesquisar">
    </form>

{% endblock body %}

oriente_web/documentos/templates/documentos/quantidade_documentos_repositorios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Repositorios</title>
</head>
<body>

{% for repositorio, valor in repositorios.items %}
    <p>
        <b>{{ repositorio }}</b>:{{ valor}}
    </p>
{% endfor %}
</body>
</html>